### PR TITLE
add min / max directives

### PR DESCRIPTION
**Pull request by rkingon**

### CODE REVIEW

**Comment by alexanderchan** [comment]
@rkingon Thanks for this!  Do you find it's too complicated to use the jquery ui date options directly to the directive? 

```
<input ui-date="{minDate: -20}"/>
```
I'm wondering if adding documentation or adding a link to documentation might serve us better than adding a new directive altogether to control something that can be done through the options.

**Comment by rkingon** [comment]
Honestly, if it can be done via the options I'd be super down with that. Will passing an options `minDate` actually follow an object an listen for changes? IE: in the new directive it'll dynamically keep the `min` or `max` date consistent with the model passed to it.

That's my only goal, so if we can achieve that natively then having it in the docs would defiantly be beneficial

**Comment by alexanderchan** [comment]
Thanks for the feedback, there was an issue raised similar to this so it definitely could use some clarification and probably an update of the example as well. There is a watcher on the options so that should update when the options change.

**Comment by rkingon** [comment]
Confirmed that it works using a model in the options param. Pretty cool.

I left an example in the `demo` folder, feel free to either close this out or leave the example in -- might be helpful to others.

thanks man, sweet plugin.

**Comment by alexanderchan** [comment]
Readme has been updated with link to jquery ui

**Comment by Devqon** [comment]
will the min- and max-date options also used in the validation of the field?

**Comment by rkingon** [comment]
@Devqon rather than allowing an incorrect date, ui-date will "disable" dates that do not validate per the min/max. Works very well, actually

**Comment by Devqon** [comment]
Yes I understand, that works perfectly. But still the user can manually type in a date before the min, which won't be picked up by angular's form validation.

**Pull request closed without merging**
