### PR TITLE
feat(timezone): Support ng-model-options timezone

### LINKED ISSUE #88: Date in UTC format
If i select  **07/16/2014** (16th July 2014), it gives a date value as **2014-07-15T18:30:00.000Z**. When i convert this string in server side in UTC format, it gives me one day before date.

### PR DESCRIPTION
**Pull request by mchapman**
Introduce support for ng-model-options timezone

Resolves #88, specifically https://github.com/angular-ui/ui-date/issues/88#issuecomment-76362914

### CODE REVIEW

**Comment by alexanderchan** [comment]
Thanks!

**Comment by MichaelBuen** [comment]
Tried ng-model-options="{timezone: '+10:00'}" an Australia/Sydney timezone

On initial load, the model is working correctly, e.g., April 22 2017 00:00 is April 21 2017 14:00. However, whenever a new date is selected, e.g., April 5 2017, the model become April 4 2017 12:00 instead of April 5 2017 14:00, then when selecting another date say April 25 2017, the model become April 25 2017 10:00 AM. The time part always decrement by two hours whenever a new date is selected.

Other detail, I'm in Asia/Manila, which is +8:00

**Comment by MichaelBuen** [comment]
Here's my patch:

```
function stringToDate(dateFormat, valueToParse, timezone) {
	dateFormat = dateFormat || uiDateFormatConfig;

	if (_angular2.default.isDate(valueToParse) && !isNaN(valueToParse)) {

		// patch
		valueToParse = new Date(valueToParse.getFullYear(), valueToParse.getMonth(), valueToParse.getDate());

		return doTZ(valueToParse, timezone);
	}
```

**Comment by MichaelBuen** [comment]
This feature does not work. 

`ng-model-options={timezone: timezoneHere}` works on HTML5's date input `<input type='date'/>`. Cannot use that though, need UI consistency with existing system, need to use the jQuery-based datepicker for angular.

@mchapman could this be fixed?

**Pull request merged**
