### PR TITLE
Timepicker

### PR DESCRIPTION
**Pull request by crowmagnumb**
Adds timepicker addon if showTime: true in your opts.

### CODE REVIEW

**Comment by nateabele** [comment]
Since this is kind of a different UI element, maybe a `uiDatetime` directive would be more appropriate? Certainly seems more declarative.

**Comment by crowmagnumb** [comment]
And then have the directives call a private function with effectively a showTime boolean (false for the orginal, true for the new directive) or some other callback function with the difference? In order to reuse all the code I'm thinking.

**Comment by crowmagnumb** [comment]
Any response to my questions above? I would like to make this pull request happen. Cheers.

**Comment by alexanderchan** [comment]
@crowmagnumb I'm a bit torn here and tend to agree with @nateabele here as this directive is just intended for making the datepicker work and keeps it simpler to only have to support jquery datepicker as the dependency.

**Comment by alexanderchan** [comment]
I would expect that there are more than just the activation of the jQuery plugin (getting and setting dates from model updates as well as tracking the various events) so for now I think it best to keep the timepicker separate.

**Pull request closed without merging**
