### PR TITLE
commonjs support

### PR DESCRIPTION
**Pull request by StefanoMagrassi**
Simple commonjs support in src/date.js

... and other little changes ;)

### CODE REVIEW

**Comment by alexanderchan** [comment]
@StefanoMagrassi this is great, thanks for all the cleanup and improvements!  I looked at the travis build and saw that all your updates seem to run.  I couldn't find any docs on the two improvements you made so that during the before-install:

    npm install -g bower grunt-cli

is no longer required.  How did you come across those tricks :smile:?  Thanks again for this.

**Comment by StefanoMagrassi** [comment]
@alexanderchan it's all about npm's "magic" scripts  ;)

take a look to the documentation:
- [scripts in package.json](https://docs.npmjs.com/files/package.json#scripts)
- [npm scripts](https://docs.npmjs.com/misc/scripts)
- [run scripts](https://docs.npmjs.com/cli/run-script)

It can also be usefull this nice guide: http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/

I'll send you asap another pull-request because I found a little bug. It is already in my forked repository.

**Comment by alexanderchan** [comment]
Very cool.  I knew you could run commands but I guess I assumed that they had to be installed globally.  I really like that they're installed just with npm and that no globals are needed.  Thanks for the links too.

**Comment by StefanoMagrassi** [comment]
You're welcome.

I saw that, thanks to Github, the pull request was merged with the bugfix I did today, so there is no need for further changes.

**Pull request merged**
